info:
  status: OK

mybatis:
  biz:
    datasource1:
       url: jdbc:mysql://localhost:3306/phr_tx_message?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
       # 下面为连接池的补充设置，应用到上面所有数据源中
       # 初始化大小，最小，最大
       initialSize: 1
       minIdle: 3
       maxActive: 20
        # 配置获取连接等待超时的时间
       maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 30000
        #validationQuery: select 'x'
       testWhileIdle: false
       testOnBorrow: false
       testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
       useGlobalDataSourceStat: true

management:
  health:
    defaults:
      enabled: true 
  endpoints:  
    web:  
      exposure:  
        include: '*'
      base-path: /
  endpoint: 
      health:
        show-details: always
spring:
  redis1 :
    cluster: 
      nodes: 192.168.68.130:7001,192.168.68.130:7002,192.168.68.130:7003
      max-redirects: 3
    timeout: 3000
    jedis:
       pool:
         max-idle: 5
         min-idle: 1
         max-active: 10
         max-wait: 5000
    host: 10.5.1.2
    port: 6379
    password: 123456
    database: 9
  cache:
    type: redis
spring:
    redis:
      #数据库索引
      database: 9
      host: 10.5.1.2
      port: 6379
      password: 123456
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000
cache: 
  redis:   #redis setting start
    enabled: true
    #缓存设置,可以直接使用应用名，如果不需要，这使用其他
    cacheName: phr
#    hostName: localhost
#    port: 6379
#    password: 
    hostName: 10.5.1.2
    port: 6379
    password: 123456
    database: 9
#    链接池
    pool:
#    最大连接数（负值表示没有限制）
      max-active: -1
#      最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
#      最大空闲链接
      max-idle: 8
#      最小空闲链接
      min-idle: 0
#    链接超时时间（毫秒）
    timeout: 3000
rocketmq:
  namesrvAddr: 192.168.68.130:9876
  #监听的队列
  listenTopicsTags1: bangsheng_data_notice_topic|auth_tags
  listenTopicsTags2: bangsheng_data_notice_topic|check_result_notice_quota_tags
  consumeThreadMin: 20
  consumeThreadMax: 40
  producerGroupName: quote-check-platform-produce-group
  mqConsumerGroupName: bangsheng_data_notice_group